### ISSUE TITLE
Revamping the Navbar: Contributing to an Open-Source Project for a Sleek and Modern Design

### ISSUE THREAD

**Issue by khurshed07** [vishal02527/My-Strength-Shree-Krishna#101]
******Before Navbar Menu change******
![Screenshot 2024-10-03 144658](https://github.com/user-attachments/assets/e23f1b59-1f08-44f3-9f6d-55ba9b0e5569)

                                                                             *******After Navbar Menu change********
![Screenshot 2024-10-03 152146](https://github.com/user-attachments/assets/60729fa6-8900-4aec-bce4-7d0270aeb282)
![Screenshot 2024-10-03 152202](https://github.com/user-attachments/assets/dc40b119-a145-46c4-93a9-6878e23cc1b1)
![Screenshot 2024-10-03 152211](https://github.com/user-attachments/assets/9d1e17d2-600c-4174-8e8f-843886315056)
![Screenshot 2024-10-03 152220](https://github.com/user-attachments/assets/e538144c-64cc-4150-ac21-6532cfe53d1f)
![Screenshot 2024-10-03 152228](https://github.com/user-attachments/assets/4bfd6ce2-f405-496d-a356-e9ec29ab5a78)

@vishal02527

I recently updated the navbar for your project to make it more attractive and user-friendly. I've attached screenshots of the changes, and I'd love to contribute this enhancement to improve the overall design.

Could you kindly assign me to this task? It would be a great opportunity for me to contribute while enhancing my skills.

Looking forward to your response!

Best regards,
Khurshed07
GitHub: https://github.com/khurshed07

**Comment by vishal02527** [comment]
@khurshed07 It's looking good. Are you sure that search bar is yet working as well as before updating navbar?

**Comment by khurshed07** [comment]
yes it's working

**Comment by khurshed07** [comment]
Hi @vishal02527
I kindly request the assignment of level 3 and [hacktoberfest-accepted] tag, as my task involves reorganizing the disarrayed menu options into a specific design layout. This change will significantly improve the user experience. Furthermore, I will be implementing CSS modifications to ensure a consistent design across all pages, enhancing both the visual appeal and usability of the website

**Comment by vishal02527** [comment]
@khurshed07 I no longer want this design. You can work on the responsiveness of the website according to the current version of repo. you can create a different issue for this. For now I am closing this issue.
