### ISSUE TITLE
Missing CONTRIBUTING.md file

### ISSUE THREAD

**Issue by archanasingh11** [vishal02527/My-Strength-Shree-Krishna#152]
**Description:**

The `CONTRIBUTING.md` file is missing from the My-Strength-Shree-Krishna repository. This file is essential for guiding new contributors through the process of setting up the project, adhering to coding standards, and submitting pull requests. Without it, contributors may lack clarity on how to effectively contribute to the project, which could lead to inconsistencies and confusion.

I recommend adding a `CONTRIBUTING.md` file to outline:
- Steps for setting up the repository locally.
- Branching and submission of pull requests.
- Code style guidelines and best practices.
- How to report issues and propose new features.

Please @vishal02527 assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2".

**Comment by vishal02527** [comment]
@archanasingh11 Also include these lines on my behalf:-

Hello everyone!

I hope you all are doing great. I want to inform you some important points that you all need to pay attention on:

Don't create similar type of issues that are already available in the issues list. If there is no issue you want to work on, only then create your own valid issue.
Please don't raise PR until you are not assigned to any issue.
Sometimes I am busy in my work, so it can take a little bit for me to response. If you are having any serious thing to share so you can ping me on LinkedIn.
At the time of raising PR, mention that issue number also.
At the time of raising PR, attach relevant screenshots or demo videos to make me cleared with your changes.
That's all. Please follow these points while contributing.

Thanks & Regards
Vishal Kumar
Project Admin, GSSoC-Ext.

**Comment by archanasingh11** [comment]
@vishal02527 Okay sure i will add this lines

**Comment by archanasingh11** [comment]
@vishal02527 if u dont mind i want to create a new issue regarding updating readme.md file.
So i request you you to assign that task to me
