### ISSUE TITLE
Adding Preloader 

### ISSUE THREAD

**Issue by VidhanThakur09** [vishal02527/My-Strength-Shree-Krishna#167]
Radhe 🪷 Radhe

### Description
The current Loading has no preloader. The screen becomes blank when the website loads. Enhancing the preloader, and improving the styling of the preloader design would greatly improve the user experience and website presentation

### Tasks:

- Redesign the preloader for better visual appeal.
- Improving the preloader.

@vishal02527   can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

**Comment by Wahidul-Haque** [comment]
I want to add animation preloader . Please assign this issue it to me @vishal02527

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me
