### ISSUE TITLE
The hover effects for the buttons in the header are not similar.

### ISSUE THREAD

**Issue by TanishSen** [vishal02527/My-Strength-Shree-Krishna#211]
<img width="1470" alt="Screenshot 2024-10-08 at 12 42 54 PM" src="https://github.com/user-attachments/assets/aad19f60-bfda-4c84-828c-c10172b8bf85">

**Comment by TanishSen** [comment]
We can make it similar .

**Comment by arpit74170** [comment]
assign this task to me ,beacause i have already done with this hover function recently in 2 projects,so i am the right person to make it good looking ,pls assign this task to me
