### ISSUE TITLE
feat : Improving footer and Navbar UI and providing hamburger menu for mobile layout

### ISSUE THREAD

**Issue by laxmanp090404** [vishal02527/My-Strength-Shree-Krishna#22]
This feature aims to enhance the visual appeal and functionality of the **footer** and **navbar** across different screen sizes. Specifically, the following improvements will be implemented:
![image](https://github.com/user-attachments/assets/3d273007-60bf-4b71-b483-d2ae7fd588cb)

### 1. **Footer UI Improvement**
   - **Responsive Design:** Refactor the footer layout to ensure it adapts seamlessly to various screen sizes (desktop, tablet, and mobile).
   - **Visual Appeal:** Optimize the design elements to make the footer more visually appealing and organized across devices.
   - **Spacing and Alignment:** Fix any issues related to alignment and spacing of elements when viewed on smaller screens, ensuring a balanced and consistent look.

### 2. **Navbar UI Enhancement**
   - **Mobile-Friendly Navbar:** Modify the navbar to ensure that it is fully responsive, with appropriate padding, spacing, and alignment.
   - **Hamburger Menu:** Implement a **hamburger menu** for the mobile layout to improve navigation on smaller devices. This will replace the existing full-width navbar for better space management and user experience.

### 3. **Expected Outcomes:**
   - Improved **visual consistency** of both the footer and navbar on all screen sizes.
   - A mobile-friendly **hamburger menu** for easier navigation.
   - Enhanced user experience with a cleaner and more responsive UI.
![image](https://github.com/user-attachments/assets/af8cfe06-d08e-47d6-be7e-9e9bba8bb139)

These changes will significantly improve the usability of the website on mobile and tablet devices, while maintaining a sleek and functional design on larger screens.

**Comment by laxmanp090404** [comment]
please add the gssoc-2024 extended label while assigning the issue

**Comment by Itachii27** [comment]
Hi @vishal02527 I want to work on this issue. Kindly assign this issue to me

**Comment by vishal02527** [comment]
@laxmanp090404 I assigned this issue to you. You can start working on it. I hope you will give a new version to the navbar and footer sections. Best of luck for that.

**Comment by laxmanp090404** [comment]
@vishal02527  Sure will work on it.

**Comment by vishal02527** [comment]
@laxmanp090404 Are you done with the task now?

**Comment by laxmanp090404** [comment]
@vishal02527  Working on it sir .Going to complete.

**Comment by laxmanp090404** [comment]
@vishal02527  There are conflicts due to previous PR. Sorry I will unable to resolve conflicts as it is focused on improving my issue.I will unable to merge this PR. Sorry for causing trouble. I would like to close this issue as it is resolved by someone else.
