### ISSUE TITLE
update mobile view navbar

### ISSUE THREAD

**Issue by jainaryan04** [vishal02527/My-Strength-Shree-Krishna#227]
the navbar in the mobile view should be visible only after the user clicks on a menu button and then it should collapse on clicking a cross button. this will enhance the UI of the site.

@vishal02527 please add gssoc-ext label.

![image](https://github.com/user-attachments/assets/a0976ea1-9feb-4bf9-9ff1-93794a93f465)

**Comment by vishal02527** [comment]
@jainaryan04 ok. I assigned it to you please implement this feature to all the available pages.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me... under gssoc-ext and hacktoberfest..

**Comment by Codersweta7** [comment]
@vishal02527 
Please assign the task to me .

**Comment by jainaryan04** [comment]
@vishal02527 
Sorry. I forgot about this. I will submit a pr asap

**Comment by Codersweta7** [comment]
@jainaryan04 
What's wrong why are you closing and opening this , can you please tell me .
