### ISSUE TITLE
Adding a dark theme 

### ISSUE THREAD

**Issue by KrishnaMohanty08** [vishal02527/My-Strength-Shree-Krishna#237]
I want to add a dark theme feature  to the page it will increase the visuality and be more comfortable for the readers

**Comment by SaanyaGarg5** [comment]
you can assign that task to me...

**Comment by KrishnaMohanty08** [comment]
could please tag the levels gssoc-extd and hackober-accepted i have resolved and conflits do check them

**Comment by KrishnaMohanty08** [comment]
@vishal02527 ??

**Comment by KrishnaMohanty08** [comment]
https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/495#issue-2593733932 please add labels to the issue

> could please tag the levels gssoc-extd and hackober-accepted i have resolved and conflits do check them

**Comment by KrishnaMohanty08** [comment]
@sahhoArjun097 can you add gssoc extd and hackober fest tags to the issue
@sanjay-kv

**Comment by sahhoArjun097** [comment]
@KrishnaMohanty08  don't tag me i am contributor too
