### ISSUE TITLE
Enhancement of Navbar

### ISSUE THREAD

**Issue by Kiran-Jadhav200** [vishal02527/My-Strength-Shree-Krishna#242]
:red_circle: **Title** :Navbar
:red_circle: **Enhancement Aim** :Makeing navbar more attrictive and responsive
:red_circle: **Changes** :  As you see in the screenshot it is not responsive let me make it more responsive and attractive 

### Screenshots 📷

![image](https://github.com/user-attachments/assets/8ef6d957-4cf5-4f14-a714-2b4c176b2b33)
![image](https://github.com/user-attachments/assets/eeba842b-873a-4da9-b6e6-f51b8bfc6d97)

**********************************************************************
✅ Details to Include When Taking the Issue:
Name : Kiran Jadhav @Kiran-Jadhav200
Participant Role (Specify the Open Source Program name, e.g., GSSOC, Hacktoberfest, etc.): GSSOC

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey. Enjoy! 😎

**Comment by SaanyaGarg5** [comment]
you can assign that task to me... under gssoc-ext and hacktoberfest.

**Comment by Kiran-Jadhav200** [comment]
Assign this task to me under GSSOC-ext
