### ISSUE TITLE
[FEAT] : Navbar Design and Usability Enhancements

### ISSUE THREAD

**Issue by ArpitaAgrahari** [vishal02527/My-Strength-Shree-Krishna#248]
![image](https://github.com/user-attachments/assets/fe07d81a-8a71-4beb-8700-084ef91b1c83)

I would like to propose a few modifications to improve the design and functionality of the current navbar:

1. Visual Hierarchy: The navigation items are currently closely packed, which affects the readability. I suggest adding more spacing between the items or increasing the padding to create a cleaner look.
2. Dropdown/Expandable Menus: For sections like "Resources" that include multiple subcategories, a dropdown or expandable menu can enhance the user experience by making navigation more intuitive and organized.
3. Alignment: The alignment of the search bar feels slightly off compared to the navigation items. A better alignment or spacing adjustment would help balance the design and make the search bar more prominent.
4. Hover Effects: Adding subtle hover effects (such as a color change or underline) when users hover over the menu items would improve interactivity and visual feedback.
5. Mobile Responsiveness: If not already implemented, I suggest making the navbar responsive for mobile devices by introducing a collapsible menu (hamburger icon) for smaller screens.

**Comment by SaanyaGarg5** [comment]
you can assign me this under gssoc-ext,hacktoberfest, label
