### ISSUE TITLE
Spelling Error on Sign-Up Page

### ISSUE THREAD

**Issue by Pragati1466** [vishal02527/My-Strength-Shree-Krishna#254]
The word "have" is misspelled, which affects the professionalism of the site.[
<img width="524" alt="Screen Shot 2024-10-09 at 6 01 14 PM" src="https://github.com/user-attachments/assets/0b16ec8b-c790-415e-93df-a3d8c4adb49b">
](url)
please assign this issue to me @vishal02527

**Comment by Pragati1466** [comment]
@vishal02527 why did you close??i found this issue and didnt get any chance its violating rules

**Comment by vishal02527** [comment]
@Pragati1466 because this issue has already been resolved by some other contributor.
