### ISSUE TITLE
Nav bar not responsive

### ISSUE THREAD

**Issue by SalehaTabassum** [vishal02527/My-Strength-Shree-Krishna#265]
When we resize the page the elements in nav bar gets over lapped.
I would like to fix this issue.
![Screenshot 2024-10-09 231711](https://github.com/user-attachments/assets/0bd3943a-1880-4c1f-9790-ad1c23bbddf4)

@vishal02527 assign this issue to me under GSSOC ext 2024 and hackatoberfest

**Comment by sakshijain432** [comment]
I would like to fix this issue.
