### ISSUE TITLE
Overlapping Content in Navbar

### ISSUE THREAD

**Issue by snehhhcodes** [vishal02527/My-Strength-Shree-Krishna#271]
The navbar is experiencing overlapping content due to insufficient spacing and sizing adjustments. The navigation links are positioned too closely together, leading to overlaps that may cause difficulty for users trying to interact with them. This issue is particularly problematic on smaller screens, where the links can become partially hidden or inaccessible, resulting in a frustrating user experience.

To resolve this issue, I can adjust the CSS styles for the navbar by increasing the padding around navigation links, ensuring they are clearly separated. I will set a maximum height for the logo to prevent excessive navbar height and use media queries to create a responsive layout for smaller screens. These changes will eliminate the overlapping content and enhance the overall usability of the navbar.

![Screenshot 2024-10-10 074728](https://github.com/user-attachments/assets/5337dacb-27a0-4920-b7d9-8222467a5448)

**Comment by snehhhcodes** [comment]
@vishal02527 if suitable please assign it to me

**Comment by snehhhcodes** [comment]
@vishal02527 any update?

**Comment by vishal02527** [comment]
@snehhhcodes Please resolve this issue across all the available pages and across all the devices like PC, tablet and mobile. Best of luck.
