### ISSUE TITLE
Enhancement: Improve Footer Section Design and Usability

### ISSUE THREAD

**Issue by T-Fathima** [vishal02527/My-Strength-Shree-Krishna#273]
### Current Situation
The footer section currently includes basic information such as "About Us," "Contact Us," and social media links. However, it lacks visual appeal and functionality.

### Proposed Enhancements
1. **Visual Design**: 
   - Update the footer background color for better contrast with text.
   - Add padding and margins to improve spacing and layout.
   - Consider using icons that are visually distinct for social media links.

2. **Content Improvement**: 
   - Provide a more descriptive "About Us" section to better inform users about the website's purpose.
   - Ensure the contact information is accurate and complete. Consider adding a contact form link for user convenience.

@vishal02527 I would like to work on this.
Please assign me this under gssoc-ext and hacktoberfest.

### Screenshots
![image](https://github.com/user-attachments/assets/9aba43e4-d657-4669-8184-1b4994bdb616)

**Comment by SaanyaGarg5** [comment]
you can assign me this under gssoc-ext,hacktoberfest,level3 label

**Comment by T-Fathima** [comment]
@vishal02527 I have resolved the conflicts and submitted the PR
Could you please review and merge under gssoc-ext level 2 and hacktoberfest.
