### ISSUE TITLE
Styling the buttons on the navbar

### ISSUE THREAD

**Issue by sahhoArjun097** [vishal02527/My-Strength-Shree-Krishna#28]
i can style the but that are on the navbar view beautiful effects.
![image](https://github.com/user-attachments/assets/9de84382-5eae-437a-aef5-240785b007f8)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and level.

**Comment by vanshikaashrma** [comment]
Hello! I’d like to take on the issue of styling the buttons on the navbar. Could you please assign it to me? I’m excited to improve the design. Thank you!

**Comment by riyarane46** [comment]
hii @vishal02527 i believe i can do this task efficiently as i have a strong hold over css styling. could you please assign me this task under GSSoC24 extd.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me..

**Comment by sahhoArjun097** [comment]
ok

**Comment by sahhoArjun097** [comment]
please check .

https://github.com/user-attachments/assets/0ba825cb-5262-4fc4-88c0-a955c1a04fc2

**Comment by sahhoArjun097** [comment]
Styling the buttons on the navbar #28 
#94
