### ISSUE TITLE
Add Scroll to top button

### ISSUE THREAD

**Issue by SurajPrakash24** [vishal02527/My-Strength-Shree-Krishna#284]
It will be very efficient for user to directly go to top of page with just one click. This button will be fixed on the page so while scrolling, it will not move.

@vishal02527 plz assign this issue to me under gssoc-ext level 2 and hacktoberfest

**Comment by rohitmore07** [comment]
Hey @vishal02527  I am very keen to work on this issue . I would be really happy if you could assign this issue to me.

**Comment by SurajPrakash24** [comment]
@rohitmore07   I have opened the issue and already asked to assign the issue to me. Plz find other issues

**Comment by rohitmore07** [comment]
@SurajPrakash24  Its none of your business. Maintainer will inform me about assigning a issue.
