### ISSUE TITLE
Improve Input boxes width properly

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vishal02527/My-Strength-Shree-Krishna#302]
![Screenshot 2024-10-10 194009](https://github.com/user-attachments/assets/759c2ab3-162f-4a48-94be-cb164726fcd9)

The input boxes on the "Contact Us" page have  width issue,  which doesn't look very good.     
I want to Fixed the issue properly.  @vishal02527  please assign me this task.

**Comment by Subhajit-2023-44** [comment]
@vishal02527 please assign me this task.

**Comment by vishal02527** [comment]
@Subhajit-2023-44 This feature has been removed. You can work on different issues or features.

**Comment by Subhajit-2023-44** [comment]
Ohh so sad three issue have been removed.    
Okay I have find another issue & sent another assign request to work on the issue, 

@vishal02527 please assign me. #311
