### ISSUE TITLE
Add a scroll back to top button

### ISSUE THREAD

**Issue by ShrishtiSingh26** [vishal02527/My-Strength-Shree-Krishna#31]
I wish to add a scroll back to top button
please assign me this issue

**Comment by vishal02527** [comment]
@ShrishtiSingh26 please implement this feature for all the pages.

**Comment by ShrishtiSingh26** [comment]
@vishal02527 please add the gssoc 2024 extd label

**Comment by vishal02527** [comment]
@ShrishtiSingh26 Are you done with the task now?

**Comment by ShrishtiSingh26** [comment]
@vishal02527  yeah it will be done by EOD

**Comment by vishal02527** [comment]
ok
