### ISSUE TITLE
 Improve Dropdown Button Styling and Hover Effect . Also improve the krishna image and btn 

### ISSUE THREAD

**Issue by ManishGupta2003** [vishal02527/My-Strength-Shree-Krishna#316]
Currently, the alignment of the image depicting "God" and the dropdown button is inconsistent. This issue aims to improve the layout by centering both elements within their parent container, enhancing the overall aesthetic and user experience   

<img width="959" alt="11 10 2024_12 52 00_REC" src="https://github.com/user-attachments/assets/bd217724-ceba-4071-ad52-b733d0e5993f">
<img width="959" alt="11 10 2024_12 52 36_REC" src="https://github.com/user-attachments/assets/fbddfe43-8200-4fff-bb8a-bbb935944da5">
can you assign me this issue for better and improve ui

**Comment by ManishGupta2003** [comment]
can you please assign me in gssoc

**Comment by ManishGupta2003** [comment]
<img width="959" alt="Screenshot 2024-10-12 154139" src="https://github.com/user-attachments/assets/c6beac5f-03f5-4152-b900-c689ab323a4b">

**Comment by ManishGupta2003** [comment]
<img width="956" alt="Screenshot 2024-10-12 154305" src="https://github.com/user-attachments/assets/41533109-48a8-4095-94b6-738731138b4a">

**Comment by ManishGupta2003** [comment]
judge me and assign me this issue . i can make responsive and attractive

**Comment by vishal02527** [comment]
@ManishGupta2003 where have you seen this drop-down button, website has no such button.

**Comment by ManishGupta2003** [comment]
in navbar all the element or link are not good looking that why i add dropdown
