### ISSUE TITLE
Creating 10 Prasad on krishna_bhog page

### ISSUE THREAD

**Issue by Codersweta7** [vishal02527/My-Strength-Shree-Krishna#320]
@vishal02527 
I want to create recipes of Prasad for Krishna ....
I will create krishna_bhog.html 
I will give a header 
I will give appropriate margins 
I will also put 10 recipes of Prasad ..of shree krishna

**Comment by SaanyaGarg5** [comment]
you can assign me this under gssoc-ext,hacktoberfest,level3 label
