### ISSUE TITLE
Adding a Places to visit page

### ISSUE THREAD

**Issue by shreya20v** [vishal02527/My-Strength-Shree-Krishna#322]
![image](https://github.com/user-attachments/assets/7c4a4807-5ed8-4d18-a11c-03ed2fcf5b06)
 Adding a new page for places to visit. On this page we can add the most popular places which tourists for eg visit. Prem Mandir, Vrindavan and Dwarkadhish Temple, Dwarka, and others. @vishal02527 please assign this to me under gssoc-ext, hacktoberfest and appropriate level.

**Comment by vishal02527** [comment]
@shreya20v As someone else is already working on this type of issue so I can't assign this issue to you. I am closing the issue, you can work on different issues.
