### ISSUE TITLE
Making the nav bar attractive for mobile screens and 
Changing the ui ux for login page 

### ISSUE THREAD

**Issue by HS202022** [vishal02527/My-Strength-Shree-Krishna#323]
![Screenshot_20241011_193042.jpg](https://github.com/user-attachments/assets/44be104b-7c1a-4d96-8142-8a9ae7d97eec)

The Nav bar must have a hamburger icon in a mobile screen or smaller screen 

![Screenshot_20241011_193140.jpg](https://github.com/user-attachments/assets/b4a5674d-acfc-4c26-98ae-ad03c629ab08)

I have a more attractive login and sign up page sample for this page 

https://github.com/user-attachments/assets/6b4bef2f-899c-4a8f-85a3-57bfcc689d14

From this video I want to add the 1 St sample of login page and add pictures or gif of Krishna Bhagwan 🙏
In the background.

**Comment by vishal02527** [comment]
@HS202022 okay, Please try to design the signup and login page according to the design mentioned in the above video. Complete it as soon as possible.
