### ISSUE TITLE
Add more Shloka in bhagavad_gita_details.html page

### ISSUE THREAD

**Issue by vishal02527** [vishal02527/My-Strength-Shree-Krishna#330]
Add some more shlokas in bhagavad_gita_details.html page in the same format which is showing in current web page.

![Screenshot 2024-10-11 225723](https://github.com/user-attachments/assets/4ee8f9d5-c8ab-4a11-a9c9-742fccd5acfb)

**Comment by abishekak18** [comment]
Sir Assign me in this project

**Comment by SaanyaGarg5** [comment]
you can assign me this task..
