### ISSUE TITLE
Add some more verses in srimad_bhagavatam_details.html page

### ISSUE THREAD

**Issue by vishal02527** [vishal02527/My-Strength-Shree-Krishna#331]
Add some more verses in srimad_bhagavatam_details.html page in the same format which is showing in current web page.

![Screenshot 2024-10-11 225826](https://github.com/user-attachments/assets/bdb96d10-4f2a-4b1c-a1a0-9c789d8b7f07)

**Comment by abishekak18** [comment]
Sir Assign me in this project.I have knowledge about srimad_bhagavatam

**Comment by SaanyaGarg5** [comment]
you can assign me this task..

**Comment by PreetiTamana** [comment]
I want to contribute in this task.
