### ISSUE TITLE
Add  more in Mahabharata section

### ISSUE THREAD

**Issue by Aditijainnn** [vishal02527/My-Strength-Shree-Krishna#334]
Add some more shlokas in Mahabharata  html page in the same format which is showing in current web page
![image](https://github.com/user-attachments/assets/115d428d-28df-4434-a9b1-1f980e30610e)
assign this to me under gssoc ext

**Comment by vishal02527** [comment]
@Aditijainnn This issue ahs already been assigned to someone else so I am closing this issue.
