### ISSUE TITLE
Made footer more appealing by adding Navbar links 

### ISSUE THREAD

**Issue by Abbas7120** [vishal02527/My-Strength-Shree-Krishna#343]
![image](https://github.com/user-attachments/assets/ef39d836-ee28-4a26-8884-f97dcc20da85)

The current website lacks a structured footer. A well-designed footer containing quick links to important pages (such as Home, Scriptures, Gallery, etc.) should be added for improved navigation and user experience. Additionally, social media links can be included to encourage engagement.

Add navigation links within the footer for easy access to important sections of the website

Assign this issue with hacktoberfest-accepted and gssoc-extd

**Comment by Abbas7120** [comment]
Work is done ! Please merge my branch

**Comment by vishal02527** [comment]
@vishal02527 please paste demo video here.
