### ISSUE TITLE
Feature Enhancement: Krishna Mandir Locator with Integrated Maps

### ISSUE THREAD

**Issue by snehhhcodes** [vishal02527/My-Strength-Shree-Krishna#350]
# Desctiption:

The proposed enhancement for the Shree Krishna website involves adding a new feature directly on the homepage that provides users with a comprehensive list of all Mandirs (temples) dedicated to Lord Krishna, along with an integrated map for each temple’s exact location. This feature will enable users to easily locate and get directions to nearby or famous Krishna temples, enhancing the site's utility and user experience right from the start.

# Benefits of the Feature:
Integrating a Krishna Mandir Locator directly on the homepage will significantly enhance the user experience by providing easy access to temple information and navigation. This feature will not only encourage users to explore and engage with local temples but also promote cultural awareness by showcasing the rich heritage associated with Lord Krishna. Additionally, it offers convenience for visitors who may be unfamiliar with their surroundings, allowing them to plan their temple visits effectively.

**Comment by snehhhcodes** [comment]
@vishal02527 if suitable assign this to me

**Comment by vishal02527** [comment]
@snehhhcodes Make sure this new page for temples should be best aligned with the website theme. And add all the necessary stuff in this page which is required. Complete it as soon as possible and attach demo video at the time of raising PR.

**Comment by snehhhcodes** [comment]
> @snehhhcodes Make sure this new page for temples should be best aligned with the website theme. And add all the necessary stuff in this page which is required. Complete it as soon as possible and attach demo video at the time of raising PR.

surely tho would be great if you can merge my earlier one PR too as thn i can sync my fork repo otherwise it will clash
