### ISSUE TITLE
Update Up Arrow Button Color to Match Website Theme

### ISSUE THREAD

**Issue by AnushkaChouhan25** [vishal02527/My-Strength-Shree-Krishna#355]
![image](https://github.com/user-attachments/assets/0419d11b-d733-4f12-be5b-66c5460c3e6b)
I propose changing the color of the up arrow button shown during scroll to better align with the website’s theme and footer for a more cohesive design. 

Please assign this issue to me under gssoc-ext, hacktoberfest, and a level 1 label.

**Comment by vishal02527** [comment]
@AnushkaChouhan25 ok and also set this top arrow button to those pages where it is not present.

**Comment by AnushkaChouhan25** [comment]
@vishal02527 Okay Sure, Thank you.

**Comment by AnushkaChouhan25** [comment]
@vishal02527 please give hactoberfest-accepted label also.
