### ISSUE TITLE
I want to change the gallery.html 

### ISSUE THREAD

**Issue by Mayanksaininh** [vishal02527/My-Strength-Shree-Krishna#380]
In the gallery section there are only some few pictures,  I want to add some more attractive picture and description about the pictures.
![Screenshot (21)](https://github.com/user-attachments/assets/52d0fbd8-a8ec-4b6f-9850-04dc6cdba0d7)

**Comment by Mayanksaininh** [comment]
Please assign this issue to me

**Comment by vishal02527** [comment]
@Mayanksaininh what changes will you make? please describe.

**Comment by Mayanksaininh** [comment]
In the gallery.html have only some picture and names. In India have lot of Krishna's temple and mostly temple have its own history 
and lot of temples were attacked by foreigners, i want to add all history behind the every picture which is in the gallery.html  and i will add more pictures.
