### ISSUE TITLE
Colouring effect on Icons hovering

### ISSUE THREAD

**Issue by Harshgupta88156** [vishal02527/My-Strength-Shree-Krishna#381]
![Screenshot 2024-10-13 104839](https://github.com/user-attachments/assets/7fcb7a6e-888c-47a0-a8f0-808f508f9b10)
While hovering in these icons, colouring is same as of main context colour, i would like to change this colour to their respective logo colour which will increase more interactiveness!!!
Assign me this project under hacktoberfest and Gssoc extd.

**Comment by Pinsu27** [comment]
assign me this issue, i'll get it resolved soon

**Comment by aadib12** [comment]
Could you please assign this issue to me? I'll make sure to resolve it promptly.
