### ISSUE TITLE
Improvement of Navbar UI

### ISSUE THREAD

**Issue by Zubaida0113** [vishal02527/My-Strength-Shree-Krishna#404]
I noticed that the navbar option is not properly aligned. Also, I would like to propose adding the favicon-like image(peacock feather) as a logo on the left div, The middle div can have navbar options and the right div will contain the search option. 
![image](https://github.com/user-attachments/assets/ae7d7168-a550-46de-917d-0177431c2880)

So I would like to work on this issue.

**Comment by Pinsu27** [comment]
assign me this issue , i'll get it resolved soon with beautiful ui

**Comment by aishwaria12** [comment]
I want do work on the same issue. Could you please assign me the work?
