### ISSUE TITLE
ADD MULTIPLE LANGUAGE TRANSLATE BUTTON 

### ISSUE THREAD

**Issue by HimangshuSharma01** [vishal02527/My-Strength-Shree-Krishna#414]
PEOPLE WHO ARE COMFORTABLE TO THEIR NATIVE LANGUAGES CAN ALSO KNOW AND LEARN IN THIS WEB PAGE BY ADDING A TRANSLATOR TOOL
![Screenshot 2024-10-14 110922](https://github.com/user-attachments/assets/56a0c51a-640a-44a7-9827-dfdb3efcf751)
I can work in this

**Comment by HS202022** [comment]
@vishal02527 please have a look
