### ISSUE TITLE
UI improvement of Discussion form

### ISSUE THREAD

**Issue by 2004shweta** [vishal02527/My-Strength-Shree-Krishna#441]
need to make form more colorful and more interactive.

**Comment by rohitmore07** [comment]
Hey @vishal02527  I am very keen to work on this issue . I would be really happy if you could assign this issue to me.

**Comment by raunikarai** [comment]
I'd love to contribute to the UI improvement of this project. Could you kindly assign me this issue related to enhancing the user interface? I have a few ideas on improving the design and user experience to make it more visually appealing and intuitive.
Looking forward to your guidance and suggestions!
thank you!
