### ISSUE TITLE
hover effect on avatars

### ISSUE THREAD

**Issue by SheetalEdu** [vishal02527/My-Strength-Shree-Krishna#448]
Hi Vishal, I'd like to suggest adding a smooth hover effect (zoom and slight transparency) to the images for a better user experience--and I'd be happy to submit a PR if you're open to it.

https://github.com/user-attachments/assets/454b8a3a-cc6a-4a40-b14a-cf4454ff4806

**Comment by rohitmore07** [comment]
Hey @vishal02527 I am very keen to work on this issue . I would be really happy if you could assign this issue to me.
