### ISSUE TITLE
enhance its visual "Shree Krishna - My Strength"

### ISSUE THREAD

**Issue by 1754riya** [vishal02527/My-Strength-Shree-Krishna#449]
Adding hover effects to "Shree Krishna - My Strength" to enhance its visual appeal.

![Uploading Screenshot (320).png…]()

@vishal02527 Please assign this to me under Gssoc'24 and hacktofest.

**Comment by sakshi-nimje** [comment]
I want to work on this issue, @vishal02527 Please assign me this issue.
I am contributing under GSSoC-ext
I am contributing under hacktoberfest
I follow contribution guidlines and code of conduct
