### ISSUE TITLE
No logo

### ISSUE THREAD

**Issue by shriyadindi** [vishal02527/My-Strength-Shree-Krishna#454]
I would like to add a logo to the website as there is no logo present, I'll design it in canva and insert it in the navbar.
![Screenshot 2024-10-15 144728](https://github.com/user-attachments/assets/6bd374b0-e347-454e-9aa6-fac6cd8111dd)

**Comment by nigam-divyanshi-dev** [comment]
@vishal02527 please assign this to me under gssoc and hacktoberfest tag..so that i can contribute...

**Comment by ashutoshak5386** [comment]
can you please assign this issue to me i would like to work on it.

**Comment by ashutoshak5386** [comment]
i have added the logo you can check once and accept the pull request

**Comment by shriyadindi** [comment]
@vishal02527 Why did you unassign me?? I've already done the task and also made the pull request!! kindly look through the pull requests..

**Comment by vishal02527** [comment]
@shriyadindi because you did not make changes as I illustrated you.

**Comment by vishal02527** [comment]
@ashutoshak5386 how far have you reached in doing this task?

**Comment by ashutoshak5386** [comment]
completed and created pr
