### ISSUE TITLE
Add Contact us page 

### ISSUE THREAD

**Issue by Anjalis14** [vishal02527/My-Strength-Shree-Krishna#470]
for any techinical issue

**Comment by Anjalis14** [comment]
@vishal02527 plz assign me this

**Comment by shauryaq05** [comment]
Please assign this this issue to me

**Comment by vishal02527** [comment]
@Anjalis14 This page should be best aligned with website theme.

**Comment by Anjalis14** [comment]
@vishal02527  yes sure

**Comment by SparshKhanna0001** [comment]
@vishal02527 the contact us page doesn't show up. Assign me this issue
