### ISSUE TITLE
Hover effects to the images 

### ISSUE THREAD

**Issue by Anjalis14** [vishal02527/My-Strength-Shree-Krishna#471]
when image is hover it should show some transition

![image](https://github.com/user-attachments/assets/b1c6041b-66f3-4bbe-af81-bcf2718936dd)

**Comment by Anjalis14** [comment]
@vishal02527 plz assign me this

**Comment by AbhayT1912** [comment]
@vishal02527 I had gone through your issue and, I request you to please assign me this I assure you that , you will definitely like my work.

**Comment by Anjalis14** [comment]
Done i will submit the PR tOmmorroo
