### ISSUE TITLE
Improper navbar Alignment

### ISSUE THREAD

**Issue by Bhoomidhanu12** [vishal02527/My-Strength-Shree-Krishna#478]
![Screenshot (337)](https://github.com/user-attachments/assets/6ad61de1-33ba-4fe5-892b-0195e44271e3)
Issue: The buttons are aligning on each other 
@vishal02527 kindly assign this issue to me

**Comment by Naveenkumar30838** [comment]
I am ready to work on this kindly assign this issue to me
