### ISSUE TITLE
Changes in the Footer with more links

### ISSUE THREAD

**Issue by RiddhiM170904** [vishal02527/My-Strength-Shree-Krishna#48]
Footer can be more descriptive and can have more links. Footer can have more information and contact details of the site.
Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest.
![image](https://github.com/user-attachments/assets/cf738aab-d017-4092-9278-d6acdf436923)

**Comment by Ppp111ppp111** [comment]
can you assign me i will do this just 2h?
