### ISSUE TITLE
Add message of not found resource.

### ISSUE THREAD

**Issue by Priyanshusharma9999** [vishal02527/My-Strength-Shree-Krishna#485]
![image](https://github.com/user-attachments/assets/4ae9f0ba-1961-4294-9a76-ffb6d6913eaf)

We can add message like this "We couldn't find what you're looking for, but the journey of faith continues! Explore other spiritual resources " when someone search those item that we don't have . 

Kindly assign me this issue under Gssoc-ext .

**Comment by vishal02527** [comment]
@Priyanshusharma9999 are you done with your work?

**Comment by Priyanshusharma9999** [comment]
@vishal02527 Yup I will make PR by tonight .

**Comment by ashutoshak5386** [comment]
can you please assign this issue to me i would like to work on it.
