### ISSUE TITLE
Wrong Redirection of Footer Icons 

### ISSUE THREAD

**Issue by RiddhiM170904** [vishal02527/My-Strength-Shree-Krishna#49]
Footer Icons redirect to the same site. Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest
![image](https://github.com/user-attachments/assets/a2293a78-9c8d-45b9-9ac9-05cd7879454b)

**Comment by vishal02527** [comment]
@RiddhiM170904 Please refer these links on the corresponding icons:-

GitHub:  https://github.com/vishal02527
Codepen:  https://codepen.io/Vishal-Kumar25
LinkedIn:  https://www.linkedin.com/in/vishal-kumar-8303a3283
