### ISSUE TITLE
Adding a enhanced hover transition to social icons

### ISSUE THREAD

**Issue by aditiverma-21** [vishal02527/My-Strength-Shree-Krishna#513]
![image](https://github.com/user-attachments/assets/14667112-2116-4f09-bb5b-812105aaa909)
To this 
![image](https://github.com/user-attachments/assets/3885837b-d5a5-4a99-9d2c-b8d8832c8098)
This hover effects to the social icons.

**Comment by sahiladit** [comment]
Can you assign it to me?
