### ISSUE TITLE
Modifying the "Read in English" button and also adding some resources to devotional resources page.

### ISSUE THREAD

**Issue by ApoorvaSunkad** [vishal02527/My-Strength-Shree-Krishna#517]
Hi,

I hope you are doing well!

Being a RadhaKrishna devotee I found this website very useful. 

I want some resources such as "Krishna Ashtakam and Radha Ashtakam" which are very powerful and one should read and understand the meaning of shlokas written in them and get benefit by reading and chanting them.

Hence I want to add these cards and a button to download PDF for above.

Also if you see the "Read in English" or "Hindi mein pade" button do not match the rest of the buttons on the website, hence I want to make the border of the button curved so that it matches the other buttons and make the UI of the website look uniform.

Please assign this issue to me under gssoc'24 and hacktoberfest label.

Thank you and I look forward to contributing.

![button](https://github.com/user-attachments/assets/28ced0cc-a4d9-4d6a-af1f-ad0a513aa218)
![resource](https://github.com/user-attachments/assets/1c7077c9-0557-468d-a065-52f9bb326a96)

**Comment by karandevhub** [comment]
\assign

**Comment by ApoorvaSunkad** [comment]
Please assign this issue to me and I'll work on it soon.
