### ISSUE TITLE
Update Current Year in the Copyright Section

### ISSUE THREAD

**Issue by koricherlasupriya** [vishal02527/My-Strength-Shree-Krishna#521]
I would like to Update Current Year in the Copyright Section Dynamically.

I would like to work on this issue. can you please assign it to me.

![Copyright year change](https://github.com/user-attachments/assets/24f5c674-e6e0-43fc-8138-f0ad8afb99c1)

**Comment by Abhijeet14d** [comment]
can you assign this issue to me

**Comment by bajajg29** [comment]
could you please assign this issue to me

**Comment by ashutoshak5386** [comment]
can you please assign this issue to me i would like to work on it.
