### ISSUE TITLE
"Other Resources" Button Not Visible on Mobile Devices

### ISSUE THREAD

**Issue by gouravi19** [vishal02527/My-Strength-Shree-Krishna#533]
I’ve noticed that the "Other Resources" button is not displaying correctly on mobile devices. As part of our effort to optimize the platform's responsiveness, I propose we address this issue. Here’s what I’ve observed and suggest:

Issue Description: The "Other Resources" button, which is visible on larger screens (desktop/tablet), is not appearing in the mobile view, leading to a lack of access to important resources for mobile users.
Proposed Solution:
Investigate the CSS or media query handling of the navigation menu to ensure the "Other Resources" button is included in the mobile version of the site.
Adjust the layout or styling so that the button is visible and accessible on all screen sizes, including mobile.
Test responsiveness to confirm that the button appears and functions correctly across different devices.
Importance: Resolving this will improve mobile users' experience by ensuring they can access all sections of the platform, including the "Other Resources" section, without limitations.

**Comment by vishal02527** [comment]
@gouravi19 please make sure that all the pages have corrected navbar. And quiz, feedback form, partner, todo list should be in other sources button. Basically there should only be other sources button, on hovering onto it then other items hould be shown in mobile screen.
