### ISSUE TITLE
Redesigning the signup form

### ISSUE THREAD

**Issue by Son7c** [vishal02527/My-Strength-Shree-Krishna#535]
This signup form looks very basic, ii would redesign it and make it look attractive

![Screenshot 2024-10-19 140236](https://github.com/user-attachments/assets/32a8b3eb-73b6-4cc4-aa94-1dfa8dcc4bb4)

@vishal02527 Please assign me this issue

**Comment by rafiya2003** [comment]
please assign me this issue
