### ISSUE TITLE
Adding A dashboard to Home page 

### ISSUE THREAD

**Issue by aditiverma-21** [vishal02527/My-Strength-Shree-Krishna#540]
![image](https://github.com/user-attachments/assets/a090bbdb-1437-4597-9b97-e4f4bdb755fd)
I saw the overlapping of the nav bar so I am suggesting to a dashboard for this for more optimized visuals

**Comment by diya-kishore** [comment]
@vishal02527 kindly assign me this issue.I llmake sure its doen ASAP

**Comment by aditiverma-21** [comment]
@vishal02527 Please check this issue as well
