### ISSUE TITLE
Navbar Alignment Issue

### ISSUE THREAD

**Issue by Karthik3904** [vishal02527/My-Strength-Shree-Krishna#541]
There is a misalignment issue in the navbar where certain menu items, such as "Feedback Form," "Partner," and "Avatars," appear to overlap or are not properly spaced. The current layout affects the visual structure and usability of the navbar.

To resolve this issue, the CSS should be updated to adjust the spacing, alignment, and responsiveness of the navbar items, ensuring proper arrangement across all screen sizes. Specifically, please correct the positioning of the "Feedback Form," "Partner," and "Avatars" buttons so they align evenly with other elements.
![Uploading Screenshot 2024-10-19 211305.png…]()

**Comment by ashutoshak5386** [comment]
can you please assign this issue to me i would like to work on it.

**Comment by Karthik3904** [comment]
@ashutoshak5386 ,
I already completed this issue and rised a pull request #581
