### ISSUE TITLE
improve to do list

### ISSUE THREAD

**Issue by JagritiChopra** [vishal02527/My-Strength-Shree-Krishna#546]
There is no option for updating the progress like marking it as complete or deleting  it .
I can fix this .Can you pls assign this under gssoc tag?

![Screenshot (181)](https://github.com/user-attachments/assets/15892657-05ef-4024-af97-5c8818aa2a74)

**Comment by ashutoshak5386** [comment]
can you please assign this issue to me i would like to work on it.

**Comment by JagritiChopra** [comment]
> can you please assign this issue to me i would like to work on it.

I am working on this its almost complete
