### ISSUE TITLE
Add more social media in footer section

### ISSUE THREAD

**Issue by itskundanhere** [vishal02527/My-Strength-Shree-Krishna#554]
I want to add more social media in the footer section like Instagram, WhatsApp and facebook.
![Screenshot 2024-10-20 200017](https://github.com/user-attachments/assets/a59d7050-8107-4926-a0b2-37df49c2a05c)

please assign me @vishal02527 please add the label.

**Comment by muskiagrwal** [comment]
i want to work on this project please assign it to me
