### ISSUE TITLE
Improvement in whole look and feel of website including increasing smoothness fixing nav bar ,adding animations and drop down buttons and little notable features 

### ISSUE THREAD

**Issue by iAbhiNaV2005** [vishal02527/My-Strength-Shree-Krishna#558]
Improvement in whole look and feel of website including fixing nav bar ,adding animations and drop down buttons and little notable features Improvement in whole look and feel of website including increasing smoothness fixing nav bar ,adding animations and drop down buttons and little notable features

**Comment by iAbhiNaV2005** [comment]
Assign it to me i will make the website look and feel better

**Comment by srajan07** [comment]
can you assign is to me please!..

**Comment by iAbhiNaV2005** [comment]
i have already all issues and planned the fixes for it you should assign it to me
