### ISSUE TITLE
 Add Prayer Counter with Bell Sound, Progress Bar, and Completion Animation

### ISSUE THREAD

**Issue by diya-kishore** [vishal02527/My-Strength-Shree-Krishna#560]
This will work on automatic count based on timer

Description:
We need to implement a prayer counter feature on the website with the following functionalities:

1. Prayer Counter: Allow users to count the number of prayers or chants, with an option to set the target to 108 or any custom number. The counter should increment with each completed chant.

2. Bell Sound : Play a customizable bell sound at the end of each count or when reaching the target. Users should be able to choose from different bell sounds.

3. Progress Bar: Display a progress bar to visually indicate how much of the target has been completed.

4. Completion Animation: Upon reaching the target, trigger a celebration animation (e.g., confetti) to give users a sense of achievement.

5. Streak Tracking: Track and display user streaks for daily or continuous usage to encourage regular practice.

6. Mantra Suggestions: Provide suggestions of popular mantras that users can select and use for their practice.

7. Customization Options:
   - Allow users to set a custom number of repetitions.
   - Provide different themes and sounds for personalization.

This feature will enhance the spiritual experience on the website, making it more engaging and motivating for users.

**Comment by diya-kishore** [comment]
@vishal02527 kindly assign me this issue. i am keen to work on this as it will provide an added benefit to user experience of the overall website.

**Comment by JahnavikaGopalbvrith** [comment]
![20241021_144257](https://github.com/user-attachments/assets/c5743947-482e-47f7-b726-3fa42deced3f)



![20241021_144803](https://github.com/user-attachments/assets/88f5c422-405d-46ba-aa77-513af5a6431a)



![20241021_144246](https://github.com/user-attachments/assets/28db5da8-4fd1-4dd3-a0f7-7d0f3b615797)



![20241021_144654](https://github.com/user-attachments/assets/3c698a26-1445-4045-afed-ff214293f7a3)


@vishal02527 I kindly request you to assign this issue.

**Comment by diya-kishore** [comment]
I would like to develop the prayer counter with an attractive UI /UX. along with the number of features mentioned above. I request you to kindly allow me to work on this issue as i am 100% sure the counter along with avrious functionalities will alow user to keep streak of the prayer

**Comment by vishal02527** [comment]
@diya-kishore please make sure the design of this feature should be responsive and attractive.
