### ISSUE TITLE
Improve Web Design

### ISSUE THREAD

**Issue by Nityaa08** [vishal02527/My-Strength-Shree-Krishna#565]
![Screenshot 2024-10-21 175303](https://github.com/user-attachments/assets/dd2c24e9-cecf-44c5-8313-ddc92b5e5f7b)

I would like to contribute to this project by improving the frontend design of the website by adding cards and colors to it. I would recommend to keep it minimalistic yet eye catching so that it attracts the user to the UI/UX of the webpage. I would request you to assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱. Thank you!

**Comment by Shubham66020** [comment]
assign this to me @Nityaa08

**Comment by arpit74170** [comment]
Please assign this task to me @vishal02527 
i will add some effect in it which make the people to connect  with is in a more visual manner , i will add hover effect with some shadows and color in it
