### ISSUE TITLE
Overlapping in header

### ISSUE THREAD

**Issue by mansiruhil13** [vishal02527/My-Strength-Shree-Krishna#575]
![Screenshot 2024-10-22 101259](https://github.com/user-attachments/assets/94236ecb-c35f-4d52-bf4b-e94707713ac7)

**Comment by mansiruhil13** [comment]
can you assign me under gssoc and hacktoberfest? @vishal02527

**Comment by devrupchowdhury** [comment]
Please assign me this @vishal02527
