### ISSUE TITLE
Improvement in the navbar of the website along with an improvement of the UI/UX

### ISSUE THREAD

**Issue by Aryan-01-star** [vishal02527/My-Strength-Shree-Krishna#583]
improvement in the navbar of the website along with an overall improvement of the UI/UX for the enhancement of the user experience and the website's overall output

![image](https://github.com/user-attachments/assets/6715533d-950f-4d7c-94a9-5617324d7f56)

**Comment by technoKC** [comment]
**What are the issues ?**
1. Navigation Bar Improvements
Font and Spacing: The font in the navigation bar (e.g., "Home," "Scriptures," "Gallery") could be made slightly larger and more evenly spaced. The current design has some overlapping and crowding, making it a bit difficult to read.
Background Contrast: The background of the navigation bar could be slightly darker or given a subtle gradient to make the text stand out better.
Icons: Adding small icons next to each navigation item would improve visual interest and make the navigation easier to interpret quickly.
2. Search Bar Optimization
Positioning: The search bar seems a bit disconnected from the rest of the navigation elements. Aligning it closer to the center or right side of the navigation bar would create a more unified look.
Placeholder Text and Icon: Adding a search icon inside the search bar along with placeholder text like "Search content..." would make it more visually engaging.
3. Header Typography
Font Weight and Color: The header "Shree Krishna - My Strength" could use a bolder font weight or a more contrasting color to make it stand out. You might also experiment with a gradient or a slight shadow effect to make it pop more against the light background.
4. Background and Contrast
The light gray textured background is subtle but might make some elements blend in too much. Either reduce the texture effect or add a faint color gradient to separate the background from the main content.
5. Image Section
Alignment and Sizing: The image of the deities is centered well, but it could benefit from a subtle border or shadow to give it a more polished look.
![Screenshot 2024-11-03 113524](https://github.com/user-attachments/assets/cca1f408-7d41-4063-8e6d-d7a93e154c45)
Please assign this to me to fix it under gssoc-ext.

**Comment by pranaydeep1** [comment]
Can u assign me this issue  @vishal02527 ?. I will resolve the navbar issue
