### ISSUE TITLE
BUG: NavBar Options On Home Page issue

### ISSUE THREAD

**Issue by Raj-Ganatra** [vishal02527/My-Strength-Shree-Krishna#586]
![issue hackober](https://github.com/user-attachments/assets/843cfa76-6b27-4864-a301-a0cd876cc8a5)

Navbar options are jumbled.
Please Label This issue as **gssoc-ext,Hackoberfest**

**Comment by Vaishnavishinde9552** [comment]
Navbar options are overlap each other. plz assign me this issue .
