### ISSUE TITLE
redesign the user feedback form

### ISSUE THREAD

**Issue by rishika105** [vishal02527/My-Strength-Shree-Krishna#590]
I think the user feedback form must be design according to the other pages to mix with the theme. It should also contain the navbar too. I want to fix that page.

![image](https://github.com/user-attachments/assets/f2c952e3-d8f7-4c54-a7ff-8139efd66916)

**Comment by vishal02527** [comment]
@rishika105 also work on its responsiveness with the mentioned issue.

**Comment by rishika105** [comment]
Ok sure!
