### ISSUE TITLE
Navigation Bar Overlap Issue

### ISSUE THREAD

**Issue by Pragati1466** [vishal02527/My-Strength-Shree-Krishna#593]
The "Avatar" element in the navigation bar is overlapping with the content of the page (like the Home or About sections). This means that the avatar is either too large, or there’s an issue with its positioning, causing it to spill over onto the next section.
<img width="1792" alt="Screen Shot 2024-10-24 at 2 18 54 AM" src="https://github.com/user-attachments/assets/20b26e8f-160f-41c4-91c8-f13b1b81afaf">
@vishal02527

**Comment by rafiya2003** [comment]
please assign me this issue
