### ISSUE TITLE
**Urgent Update**: Adjust Navbar Button Positioning!!!

### ISSUE THREAD

**Issue by charmi2109** [vishal02527/My-Strength-Shree-Krishna#601]
![image](https://github.com/user-attachments/assets/9ccb99ca-3be7-43fb-b38b-bb342a83ea75)
The buttons in the navbar are **currently** **misaligned**, creating a disorganized appearance that detracts from the website's overall aesthetic and user experience. This issue requires **immediate attention** to ensure the navbar looks clean, organized, and visually appealing. 
Proper alignment will contribute to a more polished and professional interface, enhancing the website’s usability and design coherence.
please assign me this issue @vishal02527

**Comment by miravanisri** [comment]
i like to clear this issue
