### ISSUE TITLE
Quiz Box UI Not Optimized for Dark Mode

### ISSUE THREAD

**Issue by msv6264** [vishal02527/My-Strength-Shree-Krishna#605]
When using dark mode in the quiz project, the quiz box UI lacks sufficient contrast, making it difficult to read. The background color of the quiz box and button colors don’t align well with dark mode, which affects readability. Here’s a screenshot of the current appearance in dark mode.
![Screenshot 2024-10-27 000445](https://github.com/user-attachments/assets/8f0bf029-2a3d-44a5-82cc-f7e13b4e381c)

Steps to Reproduce:

Enable dark mode
Navigate to the quiz screen
Suggested Improvement:

Update the background color of the quiz box to a darker shade to align with dark mode.
Adjust text colors to increase contrast for readability.

Additional Context: I’m participating in GirlScript Summer of Code (GSSoC) and would love to work on this issue if it’s assigned to me. If possible, could the gssoc-ext label be added to this issue if it’s approved? Thank you!

I’ve checked the open issues list but couldn’t find any similar report. However, please let me know if I missed anything, as I’m still learning!

**Comment by vishal02527** [comment]
As this issue has been resolved and PR has been merged successfully so I am closing this issue.
