### ISSUE TITLE
Make an Events Page

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [vishal02527/My-Strength-Shree-Krishna#614]
I want to make an Events Page and add the following:

- Janmashtami Countdown: Feature a countdown timer to Janmashtami with a special section dedicated to Krishna’s birth celebration.

- Event Calendar: List festivals like Govardhan Puja, Holi, and Rasa Lila with descriptions and how they're celebrated.

I want to work on this issue.

**Comment by kitiozz** [comment]
I want to work on this issue .Please assign me this issue under gssoc

**Comment by rajdeepchakraborty-rc** [comment]
@vishal02527 Could you please assign it to me so that I can start working on it?

**Comment by rajdeepchakraborty-rc** [comment]
@vishal02527 Has this been done?

**Comment by rajdeepchakraborty-rc** [comment]
@vishal02527 Could you at least provide an explanation for why it was closed? I’ve been waiting since yesterday, and it was just closed abruptly without any reason given.

**Comment by rajdeepchakraborty-rc** [comment]
I was looking forward to contributing to the repository. I apologize if my phrasing before was rude.

**Comment by rajdeepchakraborty-rc** [comment]
@vishal02527 It's fine. I would request you to add a small coment/remark while closing the issue if possible. Hope you have a great day ahead!
