### ISSUE TITLE
Bhagwat Geeta Sloka

### ISSUE THREAD

**Issue by aditiverma-21** [vishal02527/My-Strength-Shree-Krishna#62]
![image](https://github.com/user-attachments/assets/ad3916c6-c35b-44ab-8416-9ae062fb3d96)
I want to add a new feature to the website 
A Random Shloka on Each Visit: Every time someone visits or refreshes the page, a random verse from the Bhagavad Gita is displayed.
A Daily Shloka: The website shows a specific shloka for the day, which changes daily.

**Comment by sambedan1** [comment]
i add some new feature so please assign this task to me

**Comment by vishal02527** [comment]
@aditiverma-21 Radhe Radhe. Yes you can proceed. Give an unique and beautiful design for the shlokas feature. Give shlokas in Sanskrit language and also give their Hindi meanings. You can take some important and good shlokas from Bhagwadgeeta, ShrimadBhagwatam etc.
Don't forget to paste screenshot or demo video after completion of this issue. Best of luck for that.

**Comment by aditiverma-21** [comment]
Okay thank you for this

**Comment by aditiverma-21** [comment]
![image](https://github.com/user-attachments/assets/d2b3feff-28eb-4493-8737-e9fbea558b7c)
![image](https://github.com/user-attachments/assets/44921447-05b3-4698-a5d6-efabd646e57d)
I have added the sloka section into the website with the hindi meaning. Please Checkout.

**Comment by aditiverma-21** [comment]
I have added PR

**Comment by itsaryan917** [comment]
I want to add a feature  in this website in which the Bhagwad Gita Sloka will be displayed along with its hindi meaning,as u open the website

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..

**Comment by aditiverma-21** [comment]
@vishal02527 please check updated ss.

**Comment by vishal02527** [comment]
@SaanyaGarg5 Please complete this issue ASAP! The design should be more visually appealing and attractive.

**Comment by aditiverma-21** [comment]
I'm sorry but this issue was assigned to me ! Am I right?

**Comment by aditiverma-21** [comment]
@vishal02527 can I share you the demo video it's actually hovering effect and color palette I used was the same as the HOME button. I can change those if you would like.

**Comment by SaanyaGarg5** [comment]
Yes sure, I will give it to you by today..

**Comment by aditiverma-21** [comment]
@vishal02527 

https://github.com/user-attachments/assets/8060d2e4-954f-4481-9a44-0f7da9b8c05b

Please check the demo video. I change the colour to more aesthetic if you like.

**Comment by SaanyaGarg5** [comment]
I have made the changes...kindly check it and give the feedback..
THANK YOU ...

**Comment by SaanyaGarg5** [comment]
> @SaanyaGarg5 Please complete this issue ASAP! The design should be more visually appealing and attractive.

COMPLETED...Please check it..
HOPE YOU WILL LIKE IT..

**Comment by SaanyaGarg5** [comment]
@vishal02527  have you checked the design...
Please check it and give me the feedback...

**Comment by SaanyaGarg5** [comment]
@vishal02527 
Kindly respond..
