### ISSUE TITLE
adding back button to discussion forum page

### ISSUE THREAD

**Issue by Killedarswarup** [vishal02527/My-Strength-Shree-Krishna#626]
## issue: adding back button 

**screenshot**

<img width="943" alt="image" src="https://github.com/user-attachments/assets/b48eaaff-03f6-4a02-815e-97ddf27c3846">

**Comment by Killedarswarup** [comment]
please assign me for this issue

**Comment by SparshKhanna0001** [comment]
@vishal02527 assign me this. i don't think he did any work

**Comment by vishal02527** [comment]
@SparshKhanna0001 I assigned it to you. Please also remove the code of Google signin looking on signup and login forms.
