### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by Shrutibansal22** [vishal02527/My-Strength-Shree-Krishna#633]
![image](https://github.com/user-attachments/assets/a87609e3-64b9-492a-ba44-9ff5ffc4d458)
@vishal02527 
wanted to set its styling

**Comment by itsmanojcode** [comment]
I would like to request access to the Strength Shree Krishna open-source project to implement some updates to the navbar. I believe these changes will enhance user experience and improve navigation for all contributors.
Thank you for considering my request. I look forward to your response!
