### ISSUE TITLE
[bugs] the navbar is overlapping fix the ui of this  

### ISSUE THREAD

**Issue by REHAN-18** [vishal02527/My-Strength-Shree-Krishna#648]
in the navbar the menu's is overlapping I want to fix this bugs 
@vishal02527 sir pls assign me 
<img width="1360" alt="Screenshot 2024-10-29 at 5 44 08 PM" src="https://github.com/user-attachments/assets/dcbab4da-af60-4d71-8ab7-04f98c6ecb19">

**Comment by arorasneha08** [comment]
The navbar is overlapping ... Please assign me

**Comment by REHAN-18** [comment]
<img width="1434" alt="Screenshot 2024-10-30 at 11 47 43 PM" src="https://github.com/user-attachments/assets/d5b7d81f-d666-40a8-8dbb-da635f922b34">
@vishal02527 stilll this issue !!
