### ISSUE TITLE
Better UI of home page.

### ISSUE THREAD

**Issue by Rish6392** [vishal02527/My-Strength-Shree-Krishna#649]
![Screenshot 2024-10-29 182644](https://github.com/user-attachments/assets/721e3ed6-921c-4e68-af79-0280e8a81a5c)
i want to make home page look attractive by adding features like hover effect attractive colors.

**Comment by HeheAnanya** [comment]
Hi please assign this to me and a gssoc  and hacktober-fest  label on it.
