### ISSUE TITLE
Improve the header of the website 

### ISSUE THREAD

**Issue by Mansi-Tanwar** [vishal02527/My-Strength-Shree-Krishna#653]
![image](https://github.com/user-attachments/assets/ce00c62f-10d8-4faa-8a27-fb6d50245017)

The header where the home and other buttons are, is looking not so good. I would love to change it and make it spacious. I would love to work on this issue if you assign this to me under hacktoberfest. Thank You.

**Comment by NarayanRungta** [comment]
@vishal02527 I want to work on this.
