### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by kushwxha** [vishal02527/My-Strength-Shree-Krishna#673]
hey @vishal02527,
i  would like to add issue template to the repo so i would be easy for contributors to create new and descriptive issues.
so that anyone can understand issue easily.
can you please assign it to me? i would like to work on it.

**Comment by vishal02527** [comment]
@kushwxha I didn't get it. what is issue template?

**Comment by kushwxha** [comment]
https://github.com/user-attachments/assets/8775773d-f47e-41ef-8466-50c0e36e48d6

see in the above attached video, when i click on new issues i get three issue template. it is to tell which type of issue i want to report. each template would already have a decriptive text that would tell contributor what they have to add to report the issue.

**Comment by vishal02527** [comment]
As this issue has been resolved and PR has been merged successfully so I am closing this issue.
