### ISSUE TITLE
Add a Visitor Counter feature ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [vishal02527/My-Strength-Shree-Krishna#685]
I want to add a Visitor Counter feature properly.

PA please assign me this task.

**Comment by Subhajit-2023-44** [comment]
@vishal02527

**Comment by SparshKhanna0001** [comment]
@Subhajit-2023-44 @vishal02527 is this sorted?

**Comment by vishal02527** [comment]
@SparshKhanna0001 yes it has been merged.
