### ISSUE TITLE
NAVBAR AND FOOTER  

### ISSUE THREAD

**Issue by Kavish-Paraswar** [vishal02527/My-Strength-Shree-Krishna#690]
![image](https://github.com/user-attachments/assets/e455f4e7-1eb0-4777-9ba8-fce116d5dbec)
The dark mode button is not in the navbar .

![image](https://github.com/user-attachments/assets/f9f14bb3-2032-4254-83bf-f81c9742d012)
elements in the navbar is breaking making the UI bad.

![image](https://github.com/user-attachments/assets/1781ab2f-eb71-4dca-b89f-2b8e8f16d6a8)
NO footer section to this webpage.

Please assign GSOC24 And hactoberfest tags along with level 2 or level 3 to the issue.

**Comment by nihalaniharsh** [comment]
Could you please assign the issue to me ? I' am eager to drive in and make a meaningful impact .Thankyou for considering my request!"
