### ISSUE TITLE
make a uniform footer across all the pages.

### ISSUE THREAD

**Issue by rishika105** [vishal02527/My-Strength-Shree-Krishna#705]
I want to add footer to all the pages. I think some have different design some dont have it. I can add it to all pages properly.
![image](https://github.com/user-attachments/assets/a741b5c4-9967-4950-a570-456ad897fabc)
In this design I am planning to.

**Comment by vishal02527** [comment]
@rishika105 I think every page has footer.

**Comment by sikima456** [comment]
But they don't have the same design. Look I want to add this design. This is only present in feedback form page.

**Comment by rishika105** [comment]
They dont have the same design. This design I have shared is only in feedback page. Not in others. I want to add this design.
