### ISSUE TITLE
Home Page Navbar 

### ISSUE THREAD

**Issue by Abbas7120** [vishal02527/My-Strength-Shree-Krishna#708]
Responsible for fixing the UI of Navbar as its too messy and overlapped 
![image](https://github.com/user-attachments/assets/e824f720-68ad-4cf9-851f-cb30623ed258)
Assign this with level 2 and gssoc-extd

**Comment by AryanSingh1112** [comment]
hey, please assign this issue to me I will handled this and add label of gssoc-extd and level1.
