### ISSUE TITLE
CHANGING OF BACKGROUND 

### ISSUE THREAD

**Issue by BIPASHA-CHAKRABORTY** [vishal02527/My-Strength-Shree-Krishna#71]
The website is amazing but if i add a picture background instead of white and we can add more more features like adding meaning of the phrases of Bhagwadgita in English and Hindi for people to understand it better.

we can use background like this for the website -
<html>
<img src="https://media.gettyimages.com/id/929254402/photo/painting-depicting-hindu-god-krishna-playing-a-flute-outdoors-india.jpg?s=612x612&w=0&k=20&c=OvWM_77iDZ-Pte2AOySVXM1DOQCyM6-GSoj2sjX4p3s=">

</html>

Assign me this for #gssoc and #hacktoberfest

**Comment by PThanushree** [comment]
Adding attractive background can enhance the visibility and user experience. Please assign me this under gssoc-24 extnd and hactoberfest

**Comment by Deepthi-Ramineni** [comment]
Yes, adding background would be effective. Can you please this to me? I would like to work on it.
