### ISSUE TITLE
Implement "about" and "contact" buttons and their feature.

### ISSUE THREAD

**Issue by vishal02527** [vishal02527/My-Strength-Shree-Krishna#72]
Please build About and Contact buttons in the nav bar. Put About button just before the scriptures button and put contact button just after the devotional resources button.

Then implement the about page and contact page. Contact form in the contact page should be best aligned with the website them. 

NOTE: **If you are also good in backend(nodejs) then you can create a new issue for connecting the contact form to the backend.**

**Comment by surajgoraicse** [comment]
## Radhe Radhe 🩷🩷🩷

Please assign me with this issue. I will do it. 🙋‍♂️

**Comment by vishal02527** [comment]
Radhe Radhe. I assigned it to you please do it asap.

**Comment by surajgoraicse** [comment]
Sure ! 
Please check the following designs or you may provide me the design for the contact form and about. 
checkout this link https://www.freepik.com/search?format=search&query=krishna%20

![image 1](https://github.com/user-attachments/assets/d8545157-4afd-4e3e-8cb9-a3cc71a8cdf1)
![image 2](https://github.com/user-attachments/assets/7185d4be-9432-4a02-8ea2-f52deca21022)

**Comment by surajgoraicse** [comment]
## Radhe Radhe ❤️❤️

🌟**Update on the current issue**
1. Added About and Contact in the desired position in navbar in all the pages.
2.  Completed making the Contact page.

🌟 ** Progress **
1. Working on About page.

If you want any improvement then please let me know.

Screenshoot:

https://github.com/user-attachments/assets/e31f62c1-933a-4816-aa52-6fd191eeb80c

![image](https://github.com/user-attachments/assets/4efa82f7-ffd5-4b2b-91db-f473f9a72de1)

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..

**Comment by vishal02527** [comment]
@surajgoraicse Are you done with the task now?

**Comment by Codersweta7** [comment]
@vishal02527 
Please assign the task to me , I can do that .

**Comment by jjf2009** [comment]
@vishal02527 i have started to work on this today itself i create a pull

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task
