### ISSUE TITLE
🐞[BUG] Add the same header and footer to some pages

### ISSUE THREAD

**Issue by vishal02527** [vishal02527/My-Strength-Shree-Krishna#723]
Add the same header and footer to these pages:-

https://mystrengthshreekrishna.vercel.app/bhagavad_gita_details.html
https://mystrengthshreekrishna.vercel.app/srimad_bhagavatam_details.html
https://mystrengthshreekrishna.vercel.app/mahabharata_details.html
https://mystrengthshreekrishna.vercel.app/DIgital.html

**Comment by BansalAbhinav** [comment]
Hi there can you pls tell what type of footer and header you want in this, and kindly assign this issue to me.

Regards & Thanks

**Comment by vishal02527** [comment]
@BansalAbhinav you don't need to create totally new header and footer for these pages rather you have to copy and paste the same header and footer that currently the website has.

**Comment by BansalAbhinav** [comment]
@vishal02527 Thank You for assigning this issue to me

**Comment by vishal02527** [comment]
@BansalAbhinav make sure you are working on the latest version of repo. Because now navbar has been changed.

**Comment by BansalAbhinav** [comment]
@vishal02527 Thank you for the info i will do changes to the latest UI accordingly.
