### ISSUE TITLE
📄[DOCS]Updated README.md

### ISSUE THREAD

**Issue by Siddhart2004** [vishal02527/My-Strength-Shree-Krishna#730]
Added Stargazers and Forkers to README.md file 

![image](https://github.com/user-attachments/assets/b8d7ee34-d66d-40bf-a2b1-b4b6fcfa28c7)

@vishal02527 assign me this issue

**Comment by vishal02527** [comment]
@Siddhart2004 readme.md file has already contributors data so I don't think it's necessary to show stargazers and forkers separately.
