### ISSUE TITLE
🚀[FEATURE] Add popup dialogue box to prasadam recipe page

### ISSUE THREAD

**Issue by DevROHIT11** [vishal02527/My-Strength-Shree-Krishna#732]
**Is your feature request related to a problem? Please describe.**
 NO !! i woould like to add new feature to cards of prasadam in prasadam section 

**Describe the Solution You'd Like**
![Screenshot (85)](https://github.com/user-attachments/assets/3feb2f8d-81ac-46cb-9e2d-b73ee7e7878b)

I will like to add a popup dialogue box of recipes for each food item in prasadam section ,  with better UI and responsiveness also 

**Additional Context**
This is new feature request for the prasadam page @vishal02527 please assign this task to me  ASAP !!

**Comment by vishal02527** [comment]
@DevROHIT11 As this issue has been resolved and PR has been merged successfully so I am closing this issue.
