### ISSUE TITLE
Dark Mode Not Working on Home Page

### ISSUE THREAD

**Issue by kaustubh0601** [vishal02527/My-Strength-Shree-Krishna#743]
**Describe the Bug**
The dark mode toggle is not applying the dark theme to elements on the home page, resulting in an inconsistent user experience.

**Expected Behavior**
When dark mode is enabled, all elements on the home page should switch to a dark theme with appropriate colors for backgrounds, text, and icons, ensuring a cohesive and comfortable viewing experience for users in low-light environments.

**Screenshots**

https://github.com/user-attachments/assets/40492c79-a99e-442d-9982-3bfebe5e5047

**Additional Context**

**Comment by vishal02527** [comment]
@kaustubh0601 please check with other pages also, is this problem happening with them too? Fix the issue ASAP!

**Comment by Swati970** [comment]
Please assign me this issue I will work on it

**Comment by kaustubh0601** [comment]
@vishal02527  I'm working on issue. Please stay connected.

**Comment by kaustubh0601** [comment]
@vishal02527  this small bug took my lots of time. could you please add **level3** label.

**Comment by vishal02527** [comment]
As this issue has been resolved and PR has been merged successfully so I am closing this issue.
