### ISSUE TITLE
Fixed NavBar 

### ISSUE THREAD

**Issue by sahhoArjun097** [vishal02527/My-Strength-Shree-Krishna#8]
i can fix the navbar and make it responsive 
![Screenshot 2024-10-01 190738](https://github.com/user-attachments/assets/867b8f9f-543c-4257-b4c6-246e39bc0c27)
Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevan.

**Comment by CHIHNITA-REDDY-B** [comment]
I am also intrested in this can you also assign me please

Please assign this issue to me also I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevan.

**Comment by vishal02527** [comment]
@sahhoArjun097  Is this issue only with navbar?

**Comment by sahhoArjun097** [comment]
yes  i can adjust the navbar and  the elements in the navbar

**Comment by sahhoArjun097** [comment]
please add the label GSSoC 2024 Extd relaevan.

**Comment by Codewithmeowmeow** [comment]
hey kindly assign me this issue i can work on it.

**Comment by sahhoArjun097** [comment]
please check the PR i already make changes and Raise the PR
