### ISSUE TITLE
I can add more wallpapers in the 'Divine Wallpapers' section

### ISSUE THREAD

**Issue by Isham17NIT** [vishal02527/My-Strength-Shree-Krishna#9]
You can assign this issue to me. I'll add some more wallpapers.  
Please add relevant labels GSSoC 2024 Extd.
My GitHub username is Isham17NIT.

![Screenshot 2024-10-01 200000](https://github.com/user-attachments/assets/39ffb41b-3dd1-487c-bfd8-30e38445c2cb)

**Comment by vishal02527** [comment]
@Isham17NIT Make sure the wallpapers you will add should be almost same design or pattern as available on the site. You can add upto 15-20 wallpapers. Don't forget to paste screenshot or demo video after completing this issue.

**Comment by Priii-13** [comment]
please assign this issue to me .

**Comment by SaanyaGarg5** [comment]
you can assign that task to me..
